package com.example.listheadphone;
import  java.util.ArrayList;

public class HeadphoneData {
    public static String [][] data = new String[][] {
            {"SONY MDR-Z1R","The Sony MDR-Z1R is a surprising take on the high-end headphone.  Why surprising? Well instead of going for the predominantly popular open back design seen on most top-end headphones the Z1R is in fact closed back.  This makes them a whole lot more versatile when it comes to where and how you use them.", "https://images-na.ssl-images-amazon.com/images/I/41Kj2t9iAwL.jpg"},
            {"PIONEER SE-MASTER1", "After hearing these awesome open back audiophile headphones you will instantly know why they have been added to the list. Pioneer is a huge name audio brand and the SE-Master1 are just a stunning all around headphone that competes with the best of the niche brand headphones we list below. ","https://images-na.ssl-images-amazon.com/images/I/51bPTuWPllL.jpg"},
            {"SENNHEISER HD660-S","The HD 660s are more refined but still retain the slightly mid eccentric and warmer tones of the outgoing model and yet still retain incredible detail.  They are an open back headphone that pairs especially well with tube amps but are easily driven from most high resolution sources.","https://images-na.ssl-images-amazon.com/images/I/416ohhC98cL.jpg"},
            {"STAX SR009", "The Stax SR009 have a very good case for being considered the best sounding headphones in the world right now and for good reason. \n\n These electrostatic headphones will need the addition of some high-end tube amplifiers or energizers to reach their full potential but when you do set them up right you end up with a smile plastered across your face going from ear to ear.", "https://patsaudioart.com/wp-content/uploads/2015/06/Stax-SR009-mk2_600x600.jpg"},
            {"STAX SR007 MK2","If you don't have the funds to shell out over $3000 for the outstanding Stax SR-009 you could always take a look at their baby brother. \n\nWhile there was a wide gulf between the SR007 mk1 and SR009 that has now been closed considerably in the mk2 version. \n\nIf you like a more subdued midrange than the SR009 would a better choice and whilst the bass is still a little on the lean side compared to some of the Planar headphones on this list, it more than makes up for it in speed and detail retrieval.","https://images-na.ssl-images-amazon.com/images/I/413l70XLV6L.jpg"},
            {"MONOPRICE MONOLITH M1060C","Monoprice came almost out of nowhere to produce on of the most surprising headphones of recent times. \n\nThe company jumped in headfirst to the high end audiophile headphone world by releasing a range of planar magnetic headphones with open and closed back designs. \n\nOur pick of the bunch has to be the excellent Monoprice M1060C. For the cost its hard to think of anything that sound so good. It offers Audeze beating performance for a fraction of the price.","https://images-na.ssl-images-amazon.com/images/I/41LU-6oCvkL.jpg"},
            {"SENNHEISER ORPHEUS","You will most likely never own these headphones.  You will most likely never listen to these headphones. You will most likely you never even see a set of these headphones. However, from what everyone who has heard them says the new Sennheiser Orpheus are the best audiophile headphones money can buy. \n\nHow much money did you just ask?  Well in the region of $50,000.  As an exercise in how far we can take headphone technology, it's a great project but if you actually own one you should be slapped for having more money than sense. \n\nSennheiser went all out and no corners were cut in the pursuit of all-out sound fidelity.  If there was any perceived weakness Sennheiser sought to rectify it and along the way the created not just an incredibly advanced piece of audio equipment but a work of art.","https://images.squarespace-cdn.com/content/v1/53f35d9ce4b04d36ebb0b633/1479304841906-SEFZPTRNIRS7B12LF4SW/ke17ZwdGBToddI8pDm48kOTMlWjtzGLFGIEgNvPbx_EUqsxRUqqbr1mOJYKfIPR7LoDQ9mXPOjoJoqy81S2I8N_N4V1vUb5AoIIIbLZhVYxCRW4BPu10St3TBAUQYVKcPaJ58MkSAasMqx2VtCuuHd2JqTheiAyS-MamgQrTO_cvkZgue9BtWba1jl-YltaT/Sennheiser+Orpheus?format=750w"},
            {"SENNHEISER HD800S","The HD800 was for a long time considered the best audiophile headphone.  It just so happens to be one I still currently own (Update: I recently just purchased a set). However, Sennheiser did improve on the standard HD800 when they released the Sennheiser HD800s. \n\nThere wasn't much wrong with the originals but any flaws have now been ironed out leaving one of the most analytical and technically perfect sounding headphones at any price.","https://cdn.shopify.com/s/files/1/0153/8863/products/Hedaphone-Zone-Sennheiser-HD-800s-2_2000x.jpg?v=1524329466"},
            {"SENNHEISER HD820","The latest development of Sennheiser HD series of headphones is now their best and most expensive headphone (other than the Orpheus). the thing is a masterpiece and with outstanding resolution and transparency.  In fact in a world where Focal, Hifiman etc are ticking towards the $4000 mark the 820 whilst not cheap seems like a bit of a bargain since its pedigree and lineage speaks for itself.\n\nI think however that a lot of people are getting mistaken as to the performance of the HD820. These are no a 1 to 1 replacement for the original HD800 headphones. ","https://images-na.ssl-images-amazon.com/images/I/41KImeTgCML.jpg"},
            {"AUDEZE LCD-4","The top of the line Audeze LCD-4 are true luxury headphones in every sense of the word. \n\nFrom the exquisite and ornate packaging to the stellar build you are in for a treat with this set of planar magnetic beasts. \n\nTransparent, detailed fast and with excellent sound stage this is like having a full 2 way speaker system planted right on top of your head.","https://images-na.ssl-images-amazon.com/images/I/51jNIBxmk9L.jpg"}
    };
    public static ArrayList<Headphone> getListData(){
        ArrayList<Headphone> list = new ArrayList<>();
        for (String[] aData : data) {
            Headphone headphone = new Headphone();
            headphone.setNama(aData[0]);
            headphone.setInfo(aData[1]);
            headphone.setPhoto(aData[2]);
            list.add(headphone);
        }
        return list;
    }
}
